package com.zjh.distributed.model;

/**
 * @author zhaojh
 */
public class DistributedLock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributed_lock.id
     *
     * @mbg.generated Tue Nov 03 10:36:57 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributed_lock.name
     *
     * @mbg.generated Tue Nov 03 10:36:57 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributed_lock.age
     *
     * @mbg.generated Tue Nov 03 10:36:57 CST 2020
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributed_lock.id
     *
     * @return the value of distributed_lock.id
     *
     * @mbg.generated Tue Nov 03 10:36:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributed_lock.id
     *
     * @param id the value for distributed_lock.id
     *
     * @mbg.generated Tue Nov 03 10:36:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributed_lock.name
     *
     * @return the value of distributed_lock.name
     *
     * @mbg.generated Tue Nov 03 10:36:57 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributed_lock.name
     *
     * @param name the value for distributed_lock.name
     *
     * @mbg.generated Tue Nov 03 10:36:57 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributed_lock.age
     *
     * @return the value of distributed_lock.age
     *
     * @mbg.generated Tue Nov 03 10:36:57 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributed_lock.age
     *
     * @param age the value for distributed_lock.age
     *
     * @mbg.generated Tue Nov 03 10:36:57 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}