package com.zjh.xademo.model;

public class Xa129 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_129.id
     *
     * @mbg.generated Sun Nov 08 14:13:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_129.name
     *
     * @mbg.generated Sun Nov 08 14:13:00 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_129.id
     *
     * @return the value of xa_129.id
     *
     * @mbg.generated Sun Nov 08 14:13:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_129.id
     *
     * @param id the value for xa_129.id
     *
     * @mbg.generated Sun Nov 08 14:13:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_129.name
     *
     * @return the value of xa_129.name
     *
     * @mbg.generated Sun Nov 08 14:13:00 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_129.name
     *
     * @param name the value for xa_129.name
     *
     * @mbg.generated Sun Nov 08 14:13:00 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}