package com.zjh.shardingjdbcdemo.dao;

import com.zjh.shardingjdbcdemo.model.OrderItem;
import com.zjh.shardingjdbcdemo.model.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    int updateByPrimaryKey(OrderItem record);
}