package com.zjh.distributed.dao;

import com.zjh.distributed.model.DistributedLock;
import com.zjh.distributed.model.DistributedLockExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DistributedLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    long countByExample(DistributedLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    int deleteByExample(DistributedLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    int insert(DistributedLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    int insertSelective(DistributedLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    List<DistributedLock> selectByExample(DistributedLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    DistributedLock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") DistributedLock record, @Param("example") DistributedLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    int updateByExample(@Param("record") DistributedLock record, @Param("example") DistributedLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    int updateByPrimaryKeySelective(DistributedLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributed_lock
     *
     * @mbg.generated Tue Nov 03 10:41:15 CST 2020
     */
    int updateByPrimaryKey(DistributedLock record);

    DistributedLock selectDistributedLock(@Param("name") String name);
}