package com.zjh.shardingjdbcdemo.model;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_1.id
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_1.name
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_1.order_id
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item_1.user_id
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_1.id
     *
     * @return the value of t_order_item_1.id
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_1.id
     *
     * @param id the value for t_order_item_1.id
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_1.name
     *
     * @return the value of t_order_item_1.name
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_1.name
     *
     * @param name the value for t_order_item_1.name
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_1.order_id
     *
     * @return the value of t_order_item_1.order_id
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_1.order_id
     *
     * @param orderId the value for t_order_item_1.order_id
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item_1.user_id
     *
     * @return the value of t_order_item_1.user_id
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item_1.user_id
     *
     * @param userId the value for t_order_item_1.user_id
     *
     * @mbg.generated Sat Nov 07 16:23:03 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}