server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/distributed-lock?serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.zjh.distributed.dao
