package com.zjh.xademo.db130.dao;

import com.zjh.xademo.model.Xa130;
import com.zjh.xademo.model.Xa130Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Xa130Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    long countByExample(Xa130Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    int deleteByExample(Xa130Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    int insert(Xa130 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    int insertSelective(Xa130 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    List<Xa130> selectByExample(Xa130Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    Xa130 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Xa130 record, @Param("example") Xa130Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    int updateByExample(@Param("record") Xa130 record, @Param("example") Xa130Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    int updateByPrimaryKeySelective(Xa130 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_130
     *
     * @mbg.generated Sun Nov 08 14:13:38 CST 2020
     */
    int updateByPrimaryKey(Xa130 record);
}